ray:
  files_to_include:
    [
      "config.yaml",
      "config.defaults.yaml",
      "requirements.txt",
      "src",
    ]
  cluster:
    host: localhost
    port: 4000
    num_cpus: 6
  dashboard:
    host: localhost
    port: 8265

kowalski:
  protocol: https
  host: kowalski.caltech.edu
  port: 443
  token: <your_token_here>

params:
  max_queries_per_batch: 10000
  comet_list_url: https://planets.ucf.edu/resources/cometlist/
  alert_stream: ZTF_alerts
  data_path: <path_where_to_store_retrieved_data> # example: /Users/.../projects/alert-tools/data
